apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: jira-update-issues
description: "Update Jira issue fields or transition issue status"
inputs:
  jira-url:
    description: "Jira instance URL (e.g., https://your-domain.atlassian.net)"
    required: true
  jira-username:
    description: "Jira username or email address"
    required: true
  jira-token:
    description: "Jira API token"
    required: true
  issue-key:
    description: "Single issue key to update (e.g., PROJ-123). Mutually exclusive with jql."
    required: false
  jql:
    description: "JQL query to find issues to update. Mutually exclusive with issue-key."
    required: false
  update-fields:
    description: "YAML object containing fields to update"
    required: false
  transition-id:
    description: "Transition ID to apply to the issue(s)"
    required: false
  transition-name:
    description: "Transition name to apply (alternative to transition-id)"
    required: false
  max-results:
    description: "Maximum number of issues to update when using JQL"
    default: "50"
    required: false
  continue-on-error:
    description: "Whether to continue updating other issues if one fails"
    default: "true"
    required: false

outputs:
  updated-issues:
    value: ${{ steps.update-issues.outputs.updated-issues }}
    description: "JSON array of issues that were successfully updated"
  failed-updates:
    value: ${{ steps.update-issues.outputs.failed-updates }}
    description: "JSON array of issues that failed to update"
  update-count:
    value: ${{ steps.update-issues.outputs.update-count }}
    description: "Number of issues successfully updated"

runs:
  using: composite
  steps:
    - id: update-issues
      name: Update Jira Issues
      uses: docker://ldonleycb/jira-actions:latest
      shell: bash
      run: |
        /app/jira-actions update-issues \
          --url "${{ inputs.jira-url }}" \
          --username "${{ inputs.jira-username }}" \
          --token "${{ inputs.jira-token }}" \
          ${{ inputs.issue-key && format('--issue "{0}"', inputs.issue-key) || '' }} \
          ${{ inputs.jql && format('--jql "{0}"', inputs.jql) || '' }} \
          ${{ inputs.update-fields && format('--update-fields "{0}"', inputs.update-fields) || '' }} \
          ${{ inputs.transition-id && format('--transition-id "{0}"', inputs.transition-id) || '' }} \
          ${{ inputs.transition-name && format('--transition-name "{0}"', inputs.transition-name) || '' }} \
          --max-results "${{ inputs.max-results }}" \
          ${{ inputs.continue-on-error == 'false' && '--continue-on-error=false' || '' }} \
          --verbose
